AppBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CommentRepository
    manyToOne:
        author:
            targetEntity: Person
            cascade: ['persist']
        post:
            targetEntity: Post
            inversedBy: comments
            joinColumn:
                name: post_id
                referencedColumnName: id
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
        createDate:
            type: datetime
            column: create_date
    lifecycleCallbacks: {  }
