AppBundle\Entity\Person:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PersonRepository
    manyToOne:
        role:
            targetEntity: DictionaryItem
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
